const path = require('path')
const fs = require('fs')

const FUNCTIONS = path.join(__dirname, '..', 'src', 'functions')
const CLASSES = path.join(__dirname, '..', 'src', 'classes')

const INDEX = path.join(__dirname, '..', 'src', 'index.ts')

const lines = [`// Automatically generated by ./scripts/build.cjs`, '']

fs.readdir(FUNCTIONS, (err, files) => {
  files.forEach(file => {
    if (file.match(`\.spec\.`)) {
      return
    }

    lines.push(`export * from './functions/${file.replace('.ts', '')}'`)
  })

  fs.readdir(CLASSES, (err, files) => {
    files.forEach(file => {
      if (file.match(`\.spec\.`)) {
        return
      }

      lines.push(`export * from './classes/${file.replace('.ts', '')}'`)
    })

    fs.writeFile(INDEX, lines.join(`\r\n`), err => {})
  })
})
